import { Inter } from 'next/font/google'
import './globals.css'
import { ModalProvider } from './page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '顧問の玉手箱',
  description: 'Generated by 顧問の玉手箱',
  icons: '/favicon.ico'
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <ModalProvider>{children}</ModalProvider>
      </body>
    </html>
  )
}
